<a href="https://colab.research.google.com/github/Shivauppe/Data_science_python/blob/main/Python_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim ## n - dimansional array

2

In [ ]:
#matrix
# -- matrix is a special type of 2d array
mat = np.matrix([1,2,3,4,5,6,7,8])
mat

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
mat1 = np.matrix([[1,2,3],[4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
mat.ndim ## 2d array

2

In [ ]:
np.asanyarray(l) ## converts list to array

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat1) ## converts matrix to array

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.ones(1) ## 1d array

array([1.])

In [35]:
np.ones((3,4)) #2d array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.ones((1,4,2))  ## 3d array

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [41]:
arr1 = np.ones((1,2,3))

In [42]:
arr1

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
a = arr1+5
a

array([[[6., 6., 6.],
        [6., 6., 6.]]])

In [47]:
a*2

array([[[12., 12., 12.],
        [12., 12., 12.]]])

In [48]:
arr1.ndim

3

In [49]:
arr1.size ## no of elements

6

In [51]:
np.eye(3) ## identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [55]:
np.empty((3,4),dtype = int) ## random values

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408]])

In [65]:
import random

In [67]:
random.choice([1,2,3,4,5])

4

In [68]:
random.choice("Shivanand")

'S'

In [71]:
random.randrange(1,10)

6

In [73]:
random.random() #random number is generated between 0(included) and 1(excluded)

0.5372338852052394

In [79]:
arr1 = np.random.randint(1,5,size = (3,4)) #starts from 1 and ends at 5-1 and give array of shape (3,4)
arr1

array([[1, 4, 3, 4],
       [2, 4, 4, 4],
       [1, 1, 1, 1]])

In [83]:
arr1.size

12

In [84]:
arr1.reshape(4,3)

array([[1, 4, 3],
       [4, 2, 4],
       [4, 4, 1],
       [1, 1, 1]])

In [85]:
arr1.reshape(2,6)

array([[1, 4, 3, 4, 2, 4],
       [4, 4, 1, 1, 1, 1]])

In [86]:
arr1.reshape(6,2)

array([[1, 4],
       [3, 4],
       [2, 4],
       [4, 4],
       [1, 1],
       [1, 1]])

In [87]:
arr1.reshape(12,1)

array([[1],
       [4],
       [3],
       [4],
       [2],
       [4],
       [4],
       [4],
       [1],
       [1],
       [1],
       [1]])

In [88]:
arr1.reshape(1,12)

array([[1, 4, 3, 4, 2, 4, 4, 4, 1, 1, 1, 1]])

In [89]:
# reshape should be multiple of size of the array


In [25]:
arr1 = np.random.randint(1,2,(3,3))
arr2 = np.random.randint(1,2,(3,4))
arr1,arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

In [27]:
arr1 @ arr2 #matrix multiplication

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [28]:
arr1.dot(arr2) ## matrix multiplication

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])