<a href="https://colab.research.google.com/github/Shivauppe/Data_science_python/blob/main/Python_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
l = [1,2,3,4]
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim ## n - dimansional array

2

In [ ]:
#matrix
# -- matrix is a special type of 2d array
mat = np.matrix([1,2,3,4,5,6,7,8])
mat

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
mat1 = np.matrix([[1,2,3],[4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
mat.ndim ## 2d array

2

In [ ]:
np.asanyarray(l) ## converts list to array

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat1) ## converts matrix to array

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.ones(1) ## 1d array

array([1.])

In [ ]:
np.ones((3,4)) #2d array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((1,4,2))  ## 3d array

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
arr1 = np.ones((1,2,3))

In [ ]:
arr1

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a = arr1+5
a

array([[[6., 6., 6.],
        [6., 6., 6.]]])

In [ ]:
a*2

array([[[12., 12., 12.],
        [12., 12., 12.]]])

In [ ]:
arr1.ndim

3

In [ ]:
arr1.size ## no of elements

6

In [ ]:
np.eye(3) ## identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.empty((3,4),dtype = int) ## random values

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408]])

In [ ]:
import random

In [ ]:
random.choice([1,2,3,4,5])

4

In [ ]:
random.choice("Shivanand")

'S'

In [ ]:
random.randrange(1,10)

6

In [ ]:
random.random() #random number is generated between 0(included) and 1(excluded)

0.5372338852052394

In [ ]:
arr1 = np.random.randint(1,5,size = (3,4)) #starts from 1 and ends at 5-1 and give array of shape (3,4)
arr1

array([[1, 4, 3, 4],
       [2, 4, 4, 4],
       [1, 1, 1, 1]])

In [ ]:
arr1.size

12

In [ ]:
arr1.reshape(4,3)

array([[1, 4, 3],
       [4, 2, 4],
       [4, 4, 1],
       [1, 1, 1]])

In [ ]:
arr1.reshape(2,6)

array([[1, 4, 3, 4, 2, 4],
       [4, 4, 1, 1, 1, 1]])

In [ ]:
arr1.reshape(6,2)

array([[1, 4],
       [3, 4],
       [2, 4],
       [4, 4],
       [1, 1],
       [1, 1]])

In [ ]:
arr1.reshape(12,1)

array([[1],
       [4],
       [3],
       [4],
       [2],
       [4],
       [4],
       [4],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
arr1.reshape(1,12)

array([[1, 4, 3, 4, 2, 4, 4, 4, 1, 1, 1, 1]])

In [ ]:
# reshape should be multiple of size of the array


In [ ]:
arr1.reshape(2,-1) #when you donot know the rows then use -ve values

array([[1, 4, 3, 4, 2, 4],
       [4, 4, 1, 1, 1, 1]])

In [ ]:
arr1.reshape(-1,2)

array([[1, 4],
       [3, 4],
       [2, 4],
       [4, 4],
       [1, 1],
       [1, 1]])

In [ ]:
arr1.reshape(-1,-1) #invalid values

ValueError: can only specify one unknown dimension

In [ ]:
arr1.reshape(2,6).base #base is the original array

array([[1, 4, 3, 4],
       [2, 4, 4, 4],
       [1, 1, 1, 1]])

In [ ]:
arr1.reshape(1,2,6)


array([[[1, 4, 3, 4, 2, 4],
        [4, 4, 1, 1, 1, 1]]])

In [ ]:
arr1.reshape(1,2,6).ndim

3

In [ ]:
arr1.reshape(2,3,2) #multiplication should be size of array
# 3rows and 2columns repeated 2 times


array([[[1, 4],
        [3, 4],
        [2, 4]],

       [[4, 4],
        [1, 1],
        [1, 1]]])

In [ ]:
arr1.reshape(2,3,2).base #base is the original array

array([[1, 4, 3, 4],
       [2, 4, 4, 4],
       [1, 1, 1, 1]])

In [5]:
#conditions on array
arr2 = np.random.randint(1,10,(5,6))

In [6]:
arr2

array([[4, 3, 4, 7, 7, 8],
       [3, 6, 1, 3, 5, 8],
       [1, 1, 5, 6, 9, 3],
       [3, 7, 1, 2, 4, 1],
       [6, 8, 9, 5, 7, 1]])

In [ ]:
arr2.shape

(5, 6)

In [ ]:
arr2.size

30

In [7]:
#condtions
arr2[arr2>3]

array([4, 4, 7, 7, 8, 6, 5, 8, 5, 6, 9, 7, 4, 6, 8, 9, 5, 7])

In [8]:
#access the array
arr2[0][0]

4

In [9]:
arr2

array([[4, 3, 4, 7, 7, 8],
       [3, 6, 1, 3, 5, 8],
       [1, 1, 5, 6, 9, 3],
       [3, 7, 1, 2, 4, 1],
       [6, 8, 9, 5, 7, 1]])

In [17]:
arr2[0] #0th row

array([4, 3, 4, 7, 7, 8])

In [18]:
# 0th row ro 2nd row
arr2[0:3]

array([[4, 3, 4, 7, 7, 8],
       [3, 6, 1, 3, 5, 8],
       [1, 1, 5, 6, 9, 3]])

In [13]:
arr2[:,0] #0th column

array([4, 3, 1, 3, 6])

In [23]:
# 0 to 2nd row and 0th column and 2rd column
arr2[0:3,[0,2]]

array([[4, 4],
       [3, 1],
       [1, 5]])

In [26]:
#Mathematical operations
arr3 = np.random.randint(1,10,(3,3))
arr4 = np.random.randint(1,10,(3,3))

arr3,arr4

(array([[1, 1, 1],
        [3, 8, 7],
        [1, 8, 7]]),
 array([[8, 5, 7],
        [9, 6, 9],
        [3, 3, 9]]))

In [31]:
a = arr3+arr4 #addition
b = arr3-arr4 #subtraction
c = arr3*arr4 #multiplication -- based on index (Note - this is not a Matrix multiplication)
d = arr3/arr4 #division
a,b,c,d

(array([[ 9,  6,  8],
        [12, 14, 16],
        [ 4, 11, 16]]),
 array([[-7, -4, -6],
        [-6,  2, -2],
        [-2,  5, -2]]),
 array([[ 8,  5,  7],
        [27, 48, 63],
        [ 3, 24, 63]]),
 array([[0.125     , 0.2       , 0.14285714],
        [0.33333333, 1.33333333, 0.77777778],
        [0.33333333, 2.66666667, 0.77777778]]))

In [33]:
arr3/0 #infinity

<ipython-input-33-2f29f5b244c5>:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0 #infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [34]:
#Matrix Multiplication -- is a specialised 2-d array
#its different from index wise multiplication

arr3@arr4

array([[ 20,  14,  25],
       [117,  84, 156],
       [101,  74, 142]])

In [35]:
#Another Way
arr3.dot(arr4)

array([[ 20,  14,  25],
       [117,  84, 156],
       [101,  74, 142]])