<a href="https://colab.research.google.com/github/Shivauppe/Data_science_python/blob/main/Python_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim ## n - dimansional array

2

In [ ]:
#matrix
# -- matrix is a special type of 2d array
mat = np.matrix([1,2,3,4,5,6,7,8])
mat

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
mat1 = np.matrix([[1,2,3],[4,5,6]])
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
mat.ndim ## 2d array

2

In [ ]:
np.asanyarray(l) ## converts list to array

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat1) ## converts matrix to array

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.ones(1) ## 1d array

array([1.])

In [35]:
np.ones((3,4)) #2d array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.ones((1,4,2))  ## 3d array

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
arr1 = np.random.randint(1,2,(3,3))
arr2 = np.random.randint(1,2,(3,4))
arr1,arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]))

In [27]:
arr1 @ arr2 #matrix multiplication

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [28]:
arr1.dot(arr2) ## matrix multiplication

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])